# Generated by Django 3.0.5 on 2023-12-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Custom_text',
        ),
    ]
