# Generated by Django 3.0.5 on 2023-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_remove_orders_custom_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Custom_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Custom_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
