# Generated by Django 3.0.5 on 2023-12-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20231213_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Custom_text',
            field=models.CharField(default='Default Text', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Custom_text',
            field=models.CharField(default='Default Text', max_length=100),
        ),
    ]
